version: "3"
services:
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "demo"
      POSTGRES_USER: "demo"
      POSTGRES_DB: "demo"
    volumes:
      - $PWD/postgres-data:/var/lib/postgresql/data
      - $PWD/importPostgres:/data
      - $PWD/export:/export
